# Generated by Django 6.0.5 on 2026-05-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Mijoz ismi')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Jami summa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Pitsa nomi')),
                ('description', models.TextField(verbose_name='Tarkibi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Narxi (so'm)")),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sotuvda mavjud')),
            ],
            options={
                'verbose_name': 'Pitsa',
                'verbose_name_plural': 'Pitsalar',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promo kod')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Chegirma foizi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Promo Kod',
                'verbose_name_plural': 'Promo Kodlar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Narxi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Pitsa')),
            ],
            options={
                'verbose_name': 'Buyurtma qismi',
                'verbose_name_plural': 'Buyurtma qismlari',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promocode', verbose_name='Ishlatilgan promo kod'),
        ),
    ]
