# Generated by Django 6.0.3 on 2026-05-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_cancellation_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'User buyurtmalari'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Menyu cardi', 'verbose_name_plural': 'Menyu cardlari / Pitsalar'},
        ),
    ]
